services:
  server:
    image: php:8.3.19-apache-bullseye
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: facebook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
